### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by djsamlb** [tlow92/blue-iris-telegram-bot#1]
Throws the following error everytime when called:

(node:8036) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
at createError (C:\bluebot\node_modules\axios\lib\core\createError.js:16:15)
at settle (C:\bluebot\node_modules\axios\lib\core\settle.js:17:12)
at IncomingMessage.handleStreamEnd (C:\bluebot\node_modules\axios\lib\adapters\http.js:237:11)
at IncomingMessage.emit (events.js:323:22)
at endReadableNT (_stream_readable.js:1204:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:8036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see Command Line Options | Node.js v13.9.0 Documentation). (rejection id: 2)
(node:8036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8036) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Error
at open (internal/fs/promises.js:209:10)
at Object.readFile (internal/fs/promises.js:501:20)
at C:\bluebot\index.js:230:16
(node:8036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see Command Line Options | Node.js v13.9.0 Documentation). (rejection id: 5)

**Comment by tlow92** [comment]
Was fixed by using &CAM instead of %CAM which was a typo in readme.
Corrected the typo
